name: Register Deployment on GitHub

on:
  push:
    branches:
      - main

permissions:
  deployments: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          env: Production

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          status: success
          env: Production
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://aethera.vercel.app
